### ISSUE TITLE
Question about the code computing AABB of 2D Gaussian

### ISSUE THREAD

**Issue by LinzhouLi** [hbb1/diff-surfel-rasterization#15]
Hi!
Thanks for your greate work! I found that there are some artifacts where rasterasing some "long" 2D Gaussians. As the figure shows, It seems that some tiles are missing. Maybe there are something wrong when computing the tiles? And I'm confused about the code computing AABB of 2D Gaussian, Line 119 - Line 146 in `forward.cu`. Could you please explain it in more detail? 
```
__device__ bool compute_aabb(
	glm::mat3 T, 
	float2& point_image,
	float2 & extent
) {
	float3 T0 = {T[0][0], T[0][1], T[0][2]};
	float3 T1 = {T[1][0], T[1][1], T[1][2]};
	float3 T3 = {T[2][0], T[2][1], T[2][2]};

	// Compute AABB
	float3 temp_point = {1.0f, 1.0f, -1.0f};
	float distance = sumf3(T3 * T3 * temp_point);
	float3 f = (1 / distance) * temp_point;
	if (distance == 0.0) return false;

	point_image = {
		sumf3(f * T0 * T3),
		sumf3(f * T1 * T3)
	};  
	
	float2 temp = {
		sumf3(f * T0 * T0),
		sumf3(f * T1 * T1)
	};
	float2 half_extend = point_image * point_image - temp;
	extent = sqrtf2(maxf2(1e-4, half_extend));
	return true;
}
```
![image](https://github.com/hbb1/diff-surfel-rasterization/assets/71712265/0c7f60ef-6bfb-4783-a50c-79de5cbf5168)

**Comment by hbb1** [comment]
Hi, you can see here for detailed explanation. https://github.com/hbb1/diff-surfel-rasterization/issues/8
I will appreciate if you reproduce this error in the python script as it can output the bounding box, here is it https://colab.research.google.com/drive/1qoclD7HJ3-o0O1R8cvV3PxLhoDCMsH8W?usp=sharing 

Thank you!

**Comment by hbb1** [comment]
Hi, or can you export the point cloud file to me and the camera information?

**Comment by LinzhouLi** [comment]
Hi!
Thanks for your reply! I tried to reproduce the error in the colab code you provided. But I found the torch rasterizer result is not align with the CUDA rasterizer. Besides, the torch rasterizer has some error when image height != image width. So I reproduce the error with the CUDA rasterizer and here is the code:
```
import math
import torch
from diff_surfel_rasterization import GaussianRasterizationSettings, GaussianRasterizer
from torchvision.utils import save_image

def init_gaussian():
    xyz = torch.tensor([
        0, 0, 0,
        1, 0, 0,
        0, 1, 0,
        0, 0, 1,
    ], dtype=torch.float32).reshape(-1, 3)
    rot = torch.tensor([
        1, 0, 0, 0,
        1, 0, 0, 0,
        1, 0, 0, 0,
        1, 0, 0, 0
    ], dtype=torch.float32).reshape(-1, 4)
    scaling = torch.tensor([
        0.03, 0.03, 0.03,
        0.2, 0.03, 0.03,
        0.03, 0.2, 0.03,
        0.03, 0.03, 0.2
    ], dtype=torch.float32).reshape(-1, 3)[:, :2]
    opacity = torch.tensor([
        1, 1, 1, 1
    ], dtype=torch.float32).reshape(-1, 1)
    feature_dc = torch.tensor([
        1, 0, 1, 
        1, 0, 0, 
        0, 1, 0, 
        0, 0, 1, 
    ], dtype=torch.float32).reshape(-1, 1, 3)
    feature_dc = (feature_dc - 0.5) / 0.28209479177387814
    feature_rest = torch.zeros([feature_dc.shape[0], 15, 3], dtype=torch.float32)
    sh = torch.cat([feature_dc, feature_rest], dim=1)
    return xyz, rot, scaling, opacity, sh


world2view_matrix = torch.tensor([
    [-0.0577,  0.9977,  0.0355, -0.4877],
    [-0.9277, -0.0405, -0.3710,  0.6696],
    [-0.3687, -0.0543,  0.9279,  2.4655],
    [ 0.0000,  0.0000,  0.0000,  1.0000]
], device='cuda', dtype=torch.float32)

projection_matrix = torch.tensor([
    [ 0.9743,  0.0000,  0.0000,  0.0000],
    [ 0.0000,  1.7321,  0.0000,  0.0000],
    [ 0.0000,  0.0000,  1.0001, -0.0100],
    [ 0.0000,  0.0000,  1.0000,  0.0000]
], device='cuda', dtype=torch.float32)

raster_settings = GaussianRasterizationSettings(
    image_height=720,
    image_width=1280,
    tanfovx=math.tan(1.5968513788836174 * 0.5),
    tanfovy=math.tan(1.0471975511965976 * 0.5),
    bg=torch.tensor([0.0, 0.0, 0.0], device='cuda', dtype=torch.float32),
    scale_modifier=1.0,
    viewmatrix=world2view_matrix.transpose(0, 1),
    projmatrix=torch.matmul(projection_matrix, world2view_matrix).transpose(0, 1),
    sh_degree=3,
    campos=torch.tensor([1.5022,  0.6477, -2.0221], device='cuda', dtype=torch.float32),
    prefiltered=False,
    debug=False
)

xyz, rot, scaling, opacity, sh = init_gaussian()

rasterizer = GaussianRasterizer(raster_settings)
rendered, _, others = rasterizer(
    means3D = xyz.cuda(),
    means2D = None,
    shs = sh.cuda(),
    colors_precomp = None,
    opacities = opacity.cuda(),
    scales = scaling.cuda(),
    rotations = rot.cuda(),
    cov3D_precomp = None
)

raw_normal = others[2:5]
raw_normal = torch.nn.functional.normalize(raw_normal, dim=0)
raw_normal = (raw_normal + 1.0) * 0.5
save_image(raw_normal, 'test.png')
```
the full camera paramers are:
```
Camera Parameters:
width: 1280 height: 720
near: 0.01 far: 100.0
focal x: 623.5382907247958 focal y: 623.5382907247958
fov x: 1.5968513788836174 fov y: 1.0471975511965976
principal point x: 640.0 principal point y: 360.0
position: tensor([ 1.5022,  0.6477, -2.0221])
projection matrix: tensor([[ 0.9743,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.7321,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0001, -0.0100],
        [ 0.0000,  0.0000,  1.0000,  0.0000]])
view2world matrix: tensor([[-0.0577, -0.9277, -0.3687,  1.5022],
        [ 0.9977, -0.0405, -0.0543,  0.6477],
        [ 0.0355, -0.3710,  0.9279, -2.0221],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
world2view matrix: tensor([[-0.0577,  0.9977,  0.0355, -0.4877],
        [-0.9277, -0.0405, -0.3710,  0.6696],
        [-0.3687, -0.0543,  0.9279,  2.4655],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
```
and the result normal map is (missing some tiles):
![test](https://github.com/hbb1/diff-surfel-rasterization/assets/71712265/33b9224d-357a-4767-8992-f06d56cd294d)

**Comment by hbb1** [comment]
Thank you for giving me the minimal script. This would save me a lot in locating the errors. I will take time to debug.

**Comment by hbb1** [comment]
Eventually, I found the bug. In my original implementation, I calculated the AABB using the 1 sigma contour in **the object space**, and multiplied it by 3, similar to 3DGS.  However, this ignores the **perspective effect**, since the 2D Gaussian in the object space is no longer a 2D Gaussian in screen space.

**Figure A: 1 sigma aabb + 2D Gaussian (1 sigma cutoff)**
<img width="573" alt="image" src="https://github.com/hbb1/diff-surfel-rasterization/assets/57170935/0d24e3fb-db66-4fa9-96a7-9651e28fff64">

**Figure B: (1 sigma aabb) * 3 + 2D Gaussian (3 sigma cutoff)**

<img width="466" alt="image" src="https://github.com/hbb1/diff-surfel-rasterization/assets/57170935/7b6f6677-fc16-4318-b9d8-59a752e74cc5">

*incorrect, as the 2D Gaussian will not grow linearly*

**Fixed the inaccurate AABB**
However, the actual contour should be computed as the 3 sigma contour in the **object space**.
After correction.
<img width="561" alt="image" src="https://github.com/hbb1/diff-surfel-rasterization/assets/57170935/ba9052a7-0ac1-4027-a5a3-e293d89d4673">

The calculation is as follows.
![image](https://github.com/hbb1/diff-surfel-rasterization/assets/57170935/9d35c2d1-b07d-48e7-95bc-f6cc118c7518)

**Comment by hbb1** [comment]
The calculation is as follows.
![image](https://github.com/hbb1/diff-surfel-rasterization/assets/57170935/9d35c2d1-b07d-48e7-95bc-f6cc118c7518)

**Comment by LinzhouLi** [comment]
Thank you for fixing the bug! The perspective correctness of 2DGS is impressive!

**Comment by JIANG-CX** [comment]
Hi, I noticed that some parts are still missing when using the latest rasterization code. Is this expected behavior?
![test_after](https://github.com/user-attachments/assets/640b260b-7830-4818-9f07-5583a5d0ffed)

**Comment by hbb1** [comment]
@JIANG-CX This is because that the cutoff is not equal to 3 in the original backend. Please see [here](https://github.com/hbb1/diff-surfel-rasterization/pull/16) for detail.

**Comment by JIANG-CX** [comment]
Thanks for your explanation.

**Comment by huynguyenbao** [comment]
I have a question why does the code compute AABB? If the goal is to find the projection of 2D Gaussians' centers in the image plane, are the last columns of $T$, $T_3$ not enough - dividing the first and second elements with the third one to get x and y?

**Comment by hbb1** [comment]
@huynguyenbao  Hi, we should compute a tight AABB to save compute. That is, pixels outside the AABB should not be used for rasterizing the primitive.
